extensions:
    teamspeak:
        package: seyon/teamspeak3-viewer-bundle
        version: dev-master
        constraint: 
        class: Seyon\Teamspeak3\ViewerBundle\SeyonTeamspeak3ViewerBundle
        enabled: false
        name: Teamspeak Bundle
    rating:
        package: 
        version:
        constraint:
        class: SymBB\Extension\RatingBundle\SymBBExtensionRatingBundle
        enabled: true
        name: SymBB Raiting Bundle
        dir: vendor/symbb/symbb/SymBB/Extension/RatingBundle/
    bbcode:
        package: 
        version:
        constraint:
        class: SymBB\Extension\BBCodeBundle\SymBBExtensionBBCodeBundle
        enabled: true
        name: SymBB BBCode Bundle
    survey:
        package: 
        version:
        constraint:
        class: SymBB\Extension\SurveyBundle\SymBBExtensionSurveyBundle
        enabled: true
        name: SymBB Survey Bundle
        dir: vendor/symbb/symbb/SymBB/Extension/SurveyBundle/