symbb/extension-calendar:
  bundleClass: \Symbb\Extension\CalendarBundle\SymbbExtensionCalendarBundle
  composer: false
  constraint: ""
  enabled: false
  name: "SymBB Calendar"
  package: symbb/extension-calendar
  version: ""
symbb/extension-rating: 
  bundleClass: \Symbb\Extension\RatingBundle\SymbbExtensionRatingBundle
  composer: false
  constraint: ""
  enabled: true
  name: "SymBB Rating"
  package: symbb/extension-rating
  version: ""
symbb/extension-survey: 
  bundleClass: \Symbb\Extension\SurveyBundle\SymbbExtensionSurveyBundle
  composer: false
  constraint: ""
  enabled: true
  name: "SymBB Survey"
  package: symbb/extension-survey
  version: ""
symbb/extension-user-tag: 
  bundleClass: \Symbb\Extension\UserTagBundle\SymbbExtensionUserTagBundle
  composer: false
  constraint: ""
  enabled: true
  name: "SymBB User Tags"
  package: symbb/extension-user-tag
  version: ""
symbb/extension-shoutbox:
  bundleClass: \Symbb\Extension\ShoutboxBundle\SymbbExtensionShoutboxBundle
  composer: false
  constraint: ""
  enabled: true
  name: "SymBB Simple Shoutbox"
  package: symbb/extension-shoutbox
  version: ""
symbb/extension-tapatalk:
  bundleClass: \Symbb\Extension\TapatalkBundle\SymBBExtensionTapatalkBundle
  composer: true
  constraint: ""
  enabled: true
  name: "SymBB Tapatalk Extension"
  package: symbb/extension-tapatalk
  version: ""

