JMSTranslationBundle_ui:
    resource: "@JMSTranslationBundle/Controller/"
    type:     annotation
    prefix:   /_trans
    
_symbb:
    resource: "@SymBBCoreSystemBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    
    
_welcome:
    pattern:  /{_locale}/
    defaults: { _controller: SymBBCoreForumBundle:Frontend:forum }
    
_welcome_1:
    pattern:  /
    defaults: { _controller: SymBBCoreForumBundle:Frontend:forum }
    
    
