_symbb_config:
    resource: "@SymBBCoreSystemBundle/Resources/config/routing.yml"
    prefix: /forum
    
_symbb_extension_survey:
    resource: "@SymBBExtensionSurveyBundle/Resources/config/routing.yml"
    
_welcome:
    pattern:  /
    defaults: { _controller: SymBBCoreForumBundle:Frontend:forum }