_symbb:
    resource: "@SymBBCoreSystemBundle/Resources/config/routing.yml"
    prefix:   /
    
    
_welcome:
    pattern:  /{_locale}/
    defaults: { _controller: SymBBCoreForumBundle:Frontend:forum }
    
_welcome_1:
    pattern:  /
    defaults: { _controller: SymBBCoreForumBundle:Frontend:forum }
    
    
