_symbb:
    resource: "@SymbbCoreSystemBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
        
_welcome_1:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: symbb_forum_index
        permanent: true
