_symbb_config:
    resource: "@SymBBCoreConfigBundle/Resources/config/routing.yml"
    prefix: /forum
    
_symbb_post_rating:
    resource: "@SymBBPostRatingBundle/Resources/config/routing.yml"
    
_welcome:
    pattern:  /
    defaults: { _controller: SymBBCoreForumBundle:Frontend:forum }