_symbb_config:
    resource: "@SymBBCoreSystemBundle/Resources/config/routing.yml"
    prefix: /
    
_welcome:
    pattern:  /
    defaults: { _controller: SymBBCoreForumBundle:Frontend:forum }