security:
    acl:
        connection: symbb
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern:  ^/(login$|register|resetting)  
            anonymous: true
        install:
            pattern:  ^/symbb/install 
            security: false
        symbb:
            pattern: ^/
            remember_me:
              key:      "%secret%"
              lifetime: 31536000 # 365 days in seconds
              path:     /
              domain:   ~ # Defaults to the current domain from $_SERVER
            form_login:
                check_path: /login_check
                login_path: /login
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                remember_me: true
            logout:
                path:   /logout
                target: /
            anonymous: ~

    access_control:
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/symbb/install$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/acp/, role: ROLE_ADMIN }
        - { path: ^/ucp/, role: ROLE_USER }