parameters:
#    demo_page.example.class: Demo\PageBundle\Example

services:
#    demo_page.example:
#        class: %demo_page.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
